auth:
  rsa:
    publicKey: classpath:certs/public.pem
    privateKey: classpath:certs/private.pem

server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  jmx:
    enabled: true
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
