auth:
  rsa:
    publicKey: classpath:certs/public.pem
    privateKey: classpath:certs/private.pem

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  servlet:
    context-path: /api/vertical-slice
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: vertical-slice-architecture
    timezone: ${TIMEZONE:America/Sao_Paulo}
  jmx:
    enabled: true
  jpa:
    open-in-view: true
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: update
